"""Adapters that extract orchestration feedback from runtime environments.

The compatibility runtime currently talks to migrated Gym/HoloOcean envs.
Those envs expose useful fields through a mix of `info` keys and legacy
attributes.  This module centralizes that extraction so skill evaluators stay
small and independent from the simulator implementation details.
"""

from __future__ import annotations

from typing import Any

import numpy as np

from smart_captain.orchestration.feedback import FeedbackSnapshot


def _as_float_list(value: Any) -> list[float] | None:
    """Convert array-like values to plain floats for `world_state`.

    `world_state` should remain JSON-friendly because future replanning will
    likely pass it to an LLM or save it in experiment logs.  If a field cannot
    be converted safely, we return `None` and let the evaluator handle the
    missing measurement explicitly.
    """
    if value is None:
        return None
    try:
        return [float(item) for item in np.asarray(value, dtype=np.float32).reshape(-1)]
    except Exception:
        return None


def _as_float(value: Any) -> float | None:
    """Convert scalar-like values to a Python float when possible."""
    if value is None:
        return None
    try:
        return float(value)
    except Exception:
        return None


def _first_present(info: dict[str, Any], active_env: Any, *names: str) -> Any:
    """Read a value from `info` first and then from environment attributes.

    Runtime feedback can arrive in either place depending on whether the value
    is generated by `BaseEnvironment.step()` or kept as a legacy attribute.
    Keeping this lookup in one helper prevents every evaluator from learning
    those legacy naming conventions.
    """
    for name in names:
        if name in info:
            return info[name]
        if hasattr(active_env, name):
            return getattr(active_env, name)
    return None


def _nearest_obstacle_distance(info: dict[str, Any], active_env: Any) -> float | None:
    """Extract the closest range reading when the active env exposes one."""
    explicit_distance = _first_present(
        info,
        active_env,
        "nearest_obstacle_distance",
        "min_obstacle_distance",
    )
    if explicit_distance is not None:
        return _as_float(explicit_distance)

    radar_distances = getattr(active_env, "radar_intersec_dist", None)
    if radar_distances is None:
        return None

    try:
        distances = np.asarray(radar_distances, dtype=np.float32).reshape(-1)
    except Exception:
        return None

    finite_distances = distances[np.isfinite(distances)]
    if finite_distances.size == 0:
        return None
    return float(np.min(finite_distances))


def build_feedback_snapshot(
    *,
    mission_id: str,
    subtask_id: str,
    skill: str,
    step_count: int,
    observation: Any,
    reward: float | None,
    done: bool,
    truncated: bool,
    info: dict[str, Any] | None,
    active_env: Any,
    controller_skill: str | None = None,
) -> FeedbackSnapshot:
    """Build a normalized feedback object for the active subtask.

    This function is intentionally defensive.  During migration some skill envs
    may expose partial feedback, and the evaluator should be able to return a
    low-confidence `running` status instead of crashing the mission loop.
    """
    info = info or {}

    position = _as_float_list(_first_present(info, active_env, "position", "auv_position"))
    velocity = _as_float_list(_first_present(info, active_env, "velocity", "auv_relative_velocity"))
    goal = _as_float_list(_first_present(info, active_env, "goal", "goal_location"))
    distance_to_goal = _as_float(_first_present(info, active_env, "distance_to_goal", "delta_d"))

    if distance_to_goal is None and position is not None and goal is not None:
        distance_to_goal = float(np.linalg.norm(np.asarray(goal) - np.asarray(position)))

    collision_value = _first_present(info, active_env, "collision")
    goal_reached_value = _first_present(info, active_env, "goal_reached")

    return FeedbackSnapshot(
        mission_id=mission_id,
        subtask_id=subtask_id,
        skill=skill,
        step_count=step_count,
        task_skill=skill,
        controller_skill=controller_skill or skill,
        observation=observation,
        reward=_as_float(reward),
        done=bool(done),
        truncated=bool(truncated),
        info=info,
        position=position,
        velocity=velocity,
        goal=goal,
        distance_to_goal=distance_to_goal,
        collision=None if collision_value is None else bool(collision_value),
        goal_reached=None if goal_reached_value is None else bool(goal_reached_value),
        nearest_obstacle_distance=_nearest_obstacle_distance(info, active_env),
        #碰撞恢复
        collision_recovery_active=info.get("collision_recovery_active", False),
        collision_recovery_failed=info.get("collision_recovery_failed", False),
        collision_recovery_step=info.get("collision_recovery_step", 0),
        collision_count=info.get("collision_count", 0),
    )
