// MIT License (c) 2021 BYU FRoStLab see LICENSE file

#pragma once

#include "Containers/Array.h"
#include "Kismet/KismetMathLibrary.h"
#include "GameFramework/Pawn.h"
#include "HolodeckAgent.h"
#include "Octree.h"
#include "HolodeckBuoyantAgent.generated.h"

/**
 * 
 */
UCLASS()
class HOLODECK_API AHolodeckBuoyantAgent : public AHolodeckAgent{
	GENERATED_BODY()
	
public:

	virtual void BeginDestroy() override; 
	virtual void InitializeAgent() override;

	virtual void Tick(float DeltaSeconds) override;

	const float WaterDensity = 997; // kg/m^3
	float Gravity;

	UPROPERTY(BlueprintReadWrite, Category = UAVMesh)
		UStaticMeshComponent* RootMesh;

	// Physical parameters of vehicle, MUST be set in the agent definition
	float MassInKG; // in kg
	float Volume; // in m^3
	FVector CenterBuoyancy; // in cm, relative to the origin of the root mesh
	FVector CenterMass; // in cm, relative to the origin of the root mesh

	// Optional parameter to adjust the origin of the mesh relative to Unreal's body origin. 
	// Use in agent definition if the agent's mesh is not centered at the origin. 
	// NOTE: This is not currently being used, setting it for an agent will not have any effect. 
	FVector OffsetToOrigin = FVector(0, 0, 0); // in cm

	// Parameters used for surface buoyancy and thruster forces. Generated by default if not set in the agent. 
	int NumSurfacePoints = 1000;
	FBox BoundingBox = FBox();
	TArray<FVector> SurfacePoints;
	float SurfaceLevel = 0;
	
	void ApplyBuoyantForce();
	void ShowBoundingBox(float DeltaTime);
	void ShowSurfacePoints(float DeltaTime);

	Octree* makeOctree();
	// octree in global coordinates in octree
	Octree* octreeGlobal = nullptr;
	// we store the octree in the actor coordinates in octreeClean, 
	Octree* octreeLocal = nullptr;	

private:
	// Used to fix octreeGlobal 
	void updateOctree(Octree* localFrame, Octree* globalFrame);
	// Used to extract local frame from global frame
	Octree* cleanOctree(Octree* globalFrame);
};
